# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - "Casraw"
  # Maintain dependencies for docker fosscord server
  - package-ecosystem: "docker"
    directory: "/fosscord-server"
    schedule:
      interval: "daily"
    reviewers:
      - "Casraw"
  # Maintain dependencies for docker fosscord server-with-nginx
  - package-ecosystem: "docker"
    directory: "/fosscord-server-client-proxy"
    schedule:
      interval: "daily"
    reviewers:
      - "Casraw"
  # Maintain dependencies for docker fosscord client
  - package-ecosystem: "docker"
    directory: "/fosscord-client"
    schedule:
      interval: "daily"
    reviewers:
      - "Casraw"