version: "3.9"
services:
  spacebar:
    build:
      context: .
      dockerfile: Dockerfile-prod
    restart: unless-stopped
    volumes:
      - spacebar-storage:/exec/persistent/storage
    environment:
      - DATABASE=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DATABASE}
      - STORAGE_PROVIDER="file"
      - STORAGE_LOCATION="/exec/persistent/storage/"
      - PORT=${SPACEBAR_PORT}
    depends_on:
      db:
        condition: service_healthy
    labels:
      - traefik.http.services.spacebar.loadbalancer.server.scheme=http
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DATABASE:?err}
    ports:
      - '127.0.0.1:5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DATABASE} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  spacebar-storage:
  db: