name: Check pull request Server

on:
  pull_request:
    branches: [ "main" ]


jobs:

  build:
    runs-on: self-hosted
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push with postgressql
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:fosscord-server/"
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          file: Dockerfile-prod
          push: false
          tags: casraw/fosscord-server:latest-postgressql
      -
        name: Build and push with sqlite
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:fosscord-server/"
          file: Dockerfile
          push: false
          tags: casraw/fosscord-server:latest-sqlite